pipeline {
agent any

tools {
maven 'Mavenone' // the Maven name configured in Jenkins
jdk 'JDK21' // replace with the JDK name in Jenkins
}

stages {
stage('Clone Repository') {
steps {
git branch: 'main', url: 'https://github.com/sapna-surendran/java-ci-pipel.git'
}
}

stage('Build') {
steps {
sh 'mvn clean compile'
}
}

stage('Test') {
steps {
sh 'mvn test'
}
post {
always {
junit 'target/surefire-reports/*.xml'
}
}
}

stage('Report') {
steps {
echo "Build completed successfully!"
}
}
}

post {
success {
echo 'Pipeline executed successfully!'
}
failure {
echo 'Build failed. Check logs for details.'
}
}
}
